# Generated by CMake, DO NOT EDIT
CMakeFiles/cmake.check_cache: \
/Users/saturnman/projects/clucene-core-2.3.3.4/cmake/DefineOptions.cmake\
/Users/saturnman/projects/clucene-core-2.3.3.4/src/test/CMakeLists.txt\
/opt/local/share/cmake-2.8/Modules/CMakeParseArguments.cmake\
/opt/local/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake\
/opt/local/share/cmake-2.8/Modules/FindPackageMessage.cmake\
/opt/local/share/cmake-2.8/Modules/FindZLIB.cmake
	/opt/local/bin/cmake -H/Users/saturnman/projects/clucene-core-2.3.3.4 -B/Users/saturnman/projects/clucene-core-2.3.3.4/build-ios
