# Generated by CMake, DO NOT EDIT
CMakeFiles/cmake.check_cache: \
/Users/saturnman/projects/clucene-core-2.3.3.4/cmake/DefineOptions.cmake\
/Users/saturnman/projects/clucene-core-2.3.3.4/src/core/CMakeLists.txt\
/Users/saturnman/projects/clucene-core-2.3.3.4/src/core/libclucene-core.pc.cmake
	/opt/local/bin/cmake -H/Users/saturnman/projects/clucene-core-2.3.3.4 -B/Users/saturnman/projects/clucene-core-2.3.3.4/build-ios
